job('Ansible-users-dsl') {

	description('Ansible job generated by DSL')
	parameters {
		choiceParam('AGE', ['21', '22', '23','24','25'])
	}	
	
	steps {
          wrappers {
		colorizeOutput(colorMap = 'xterm')
        	}
	
	  ansiblePlaybook('/var/jenkins_home/ansible/people.yml') {
		inventoryPath('/var/jenkins_home/ansible/hosts')
		colorizeOutput(true)
		extraVars {
			extraVar("PEOPLE_AGE",'${AGE}',false)
		}
	  }
	}
         
}
